### ISSUE TITLE
JavaScript 1.8: repeat

### ISSUE THREAD

**Issue by sphenk** [guipn/sinful.js#23]
Hi Guilherme,

JavaScript 1.8 implements your repeat function.
The Error you throw on this, you may want to change into a console warning.

Cheers,

Henk

**Comment by guipn** [comment]
Heya Henk,

I expect a considerable amount of these functions to exist at a certain point, or within certain contexts.

The way of treating conflicts, however, is very flexible, because you can easily change the way in which sinful augments its universe, by modifying the `bless` function.

A detailed (and very short) explanation with a practical example exists in our wiki: https://github.com/guipn/sinful.js/wiki/Usage

Hope that's useful!

Take care.
